---
- name: Config kubeadm images
  command: kubeadm config images pull

- name: Initialize the Kubernetes cluster using kubeadm
  command: kubeadm init --apiserver-advertise-address="{{ node_ip }}" --apiserver-cert-extra-sans="{{ node_ip }}" --node-name k8s-master --pod-network-cidr="{{ pod_cidr }}"

- name: Setup kubeconfig for vagrant user
  command: "{{ item }}"
  with_items:
    - mkdir -p /home/vagrant/.kube
    - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
    - chown vagrant:vagrant /home/vagrant/.kube/config

- name: Install calico pod network
  become: false
  command: kubectl create -f https://docs.projectcalico.org/manifests/calico.yaml

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file
  copy: content="{{ join_command.stdout_lines[0] }}" dest="./output/join-command"
  delegate_to: 127.0.0.1
  become: false

- name: Copy kubeconfig to local file
  fetch:
    src: /home/vagrant/.kube/config
    dest: ./output/config
    flat: yes